name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - kuukiyomi
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            gofiles:
              - 'go/**'
  
  
      - name: Set up Go
        if: steps.filter.outputs.gofiles == 'true'
        uses: actions/setup-go@v2
        with:
          go-version: '1.21' 
  
      - name: Install Android SDK
        if: steps.filter.outputs.gofiles == 'true'
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30' 
  
      - name: Install Android NDK
        if: steps.filter.outputs.gofiles == 'true'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
  
      - name: Install GoMobile
        if: steps.filter.outputs.gofiles == 'true'
        run: go install golang.org/x/mobile/cmd/gomobile@latest
  
      - name: Build GoMobile app
        if: steps.filter.outputs.gofiles == 'true'
        run: |
          cd go/torrserver
          go get golang.org/x/mobile/bind
          gomobile init
          cd bindings
          gomobile bind -target=android -androidapi 23 -ldflags "-s -w" -o ../../../app/libs/server.aar
  
      - name: Commit build library
        if: steps.filter.outputs.gofiles == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add app/libs/server.aar
          git add app/libs/server-sources.jar
          git commit -m "Add compiled torrserver library"
        
      - name: Push changes
        if: steps.filter.outputs.gofiles == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: kuukiyomi


      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set ACRA properties
        env:
          acraUri: ${{ secrets.ACRA_URI }}
          acraLogin: ${{ secrets.ACRA_LOGIN }}
          acraPassword: ${{ secrets.ACRA_PASSWORD }}
        run: |
          echo "ACRA_URI=$acraUri" >> acra.properties
          echo "ACRA_LOGIN=$acraLogin" >> acra.properties
          echo "ACRA_PASSWORD=$acraPassword" >> acra.properties

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: ktlintCheck assembleStandardRelease testReleaseUnitTest

      # Sign APK and create release for tags

      - name: Get tag name

        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LuftVerbot/kuukiyomi'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LuftVerbot/kuukiyomi'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LuftVerbot/kuukiyomi'
        run: |
          set -e

          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk kuukiyomi-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum kuukiyomi-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk kuukiyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum kuukiyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk kuukiyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum kuukiyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk kuukiyomi-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum kuukiyomi-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk kuukiyomi-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum kuukiyomi-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LuftVerbot/kuukiyomi'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Kuukiyomi ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }}
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
          files: |
            kuukiyomi-${{ env.VERSION_TAG }}.apk
            kuukiyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
            kuukiyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            kuukiyomi-x86-${{ env.VERSION_TAG }}.apk
            kuukiyomi-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
