name: Build and Release

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    name: Build and Release App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17  # Change this to your desired Java version
          distribution: adopt

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleStandardPreview 

      - name: Get Latest Tag
        id: latest_tag
        run: |
          # Get the latest tag or use a fallback value
          latest_tag=$(git describe --abbrev=0 --tags || echo "v1.0.0")
          echo "TAG=$latest_tag" >> $GITHUB_ENV  # Set the environment variable
      
      - name: List APK Files
        run: ls -R app/build/outputs/apk/standard/release/

      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned.apk
            app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned.apk
            app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned.apk
            app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned.apk
            app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned.apk
          tag_name: ${{ env.TAG }}
          name: femiyomi Release - ${{ env.TAG }}
          draft: false  # Set to 'true' if you want to create draft releases
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
